<a href="https://colab.research.google.com/github/hvjha/AWA/blob/Python/class_24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

series means one dimension labeled array, capable of holding any data type it can be integer
 it can be string it can be float . similar to  list in python , column in spread sheet but
 with labeled indexes.

In [3]:
s = pd.Series([3,-5,7,4])
print(s)

0    3
1   -5
2    7
3    4
dtype: int64

In [4]:
S = pd.Series([3,-5,7,4], index=['a','b','c','d'])
print(S)

a    3
b   -5
c    7
d    4
dtype: int64

```
Data Frame is nothing but a two dimensional labeled data Structure like Excel
```

In [7]:
data = {'Name':['Tom','Jack','Steve','Ricky'],'Age':[28,34,29,42], 'Id':[1,2,3,4]}
print(data)
df = pd.DataFrame(data)
print(df)

{'Name': ['Tom', 'Jack', 'Steve', 'Ricky'], 'Age': [28, 34, 29, 42], 'Id': [1, 2, 3, 4]}
    Name  Age  Id
0    Tom   28   1
1   Jack   34   2
2  Steve   29   3
3  Ricky   42   4

In [8]:
df.head()

    Name  Age  Id
0    Tom   28   1
1   Jack   34   2
2  Steve   29   3
3  Ricky   42   4

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   Id      4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [10]:
df.describe()

             Age        Id
count   4.000000  4.000000
mean   33.250000  2.500000
std     6.396614  1.290994
min    28.000000  1.000000
25%    28.750000  1.750000
50%    31.500000  2.500000
75%    36.000000  3.250000
max    42.000000  4.000000

In [12]:
df[['Name','Age','Id']].head(2)

   Name  Age  Id
0   Tom   28   1
1  Jack   34   2

In [13]:
df[['Name','Age','Id']].tail(2)

    Name  Age  Id
2  Steve   29   3
3  Ricky   42   4

```
loc - label based Indexing
iloc - integer(Position) based indexing

In loc when we perform slicing then end point is
Included but in iloc excluded the end point
```

In [14]:
data = {'Name':['Aman','Harsh','Ankit','Adarsh'],'Age':[23,24,22,21], 'Id':[1,2,3,4]}
df = pd.DataFrame(data,index=['a','b','c','d'])
print(df)

     Name  Age  Id
a    Aman   23   1
b   Harsh   24   2
c   Ankit   22   3
d  Adarsh   21   4

In [15]:
df.head()

     Name  Age  Id
a    Aman   23   1
b   Harsh   24   2
c   Ankit   22   3
d  Adarsh   21   4

In [16]:
df.loc['a']

Name    Aman
Age       23
Id         1
Name: a, dtype: object

In [17]:
df.iloc[1]

Name    Harsh
Age        24
Id          2
Name: b, dtype: object

In [18]:
df.loc['a':'c']

    Name  Age  Id
a   Aman   23   1
b  Harsh   24   2
c  Ankit   22   3

In [19]:
df.iloc[0:2]

    Name  Age  Id
a   Aman   23   1
b  Harsh   24   2

```
**Reading Data Set**
What type of data type we read ?
CSV, xlxs, json, parquet
```

In [20]:
from google.colab import files
uploaded = files.upload()

Saving Barclays Financial Transactional Data.xlsx to Barclays Financial Transactional Data.xlsx

In [42]:
df = pd.read_excel('Barclays Financial Transactional Data.xlsx')
df.head(5)

,TransactionID,CustomerID,AccountID,AccountType,TransactionType,Product,Firm,Region,Manager,TransactionDate,TransactionAmount,AccountBalance,RiskScore,CreditRating,TenureMonths
0,118,CUST3810,ACC49774,Savings,Deposit,Credit Card,Firm D,West,Manager 4,2024-08-01 00:00:00,20664.409820,88483.42208,0.483333,522,29
1,102,CUST3109,ACC96277,Savings,Deposit,Mutual Fund,Firm B,North,Manager 4,17-12-2023,94924.359120,56670.15864,0.788989,686,130
2,151,CUST2626,ACC21429,Credit,Payment,Personal Loan,Firm C,West,Manager 1,22-05-2024,-7871.160407,84968.05587,0.547782,618,157
3,57,CUST3725,ACC48501,Loan,Withdrawal,Credit Card,Firm A,East,Manager 4,24-12-2023,24979.808160,115196.96420,0.125587,803,155
4,113,CUST4258,ACC11285,Loan,Transfer,Home Loan,Firm A,West,Manager 4,15-01-2023,72890.748550,111602.76610,1.048787,657,68

In [30]:
from google.colab import files
uploaded = files.upload()

Saving SalesData.csv to SalesData.csv

In [40]:
df = pd.read_csv("SalesData.csv", encoding="latin1")
df.head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,TEC-PH-5816,Technology,Phones,Samsung Convoy 3,$221.98,2,0.0,$62.15,40.77,High
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,FUR-CH-5379,Furniture,Chairs,"Novimex Executive Leather Armchair, Black","$3,709.40",9,0.1,($288.77),923.63,Critical
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,...,TEC-PH-5356,Technology,Phones,"Nokia Smart Phone, with Caller ID","$5,175.17",9,0.1,$919.97,915.49,Medium
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,NaN,Berlin,...,TEC-PH-5267,Technology,Phones,"Motorola Smart Phone, Cordless","$2,892.51",5,0.1,($96.54),910.16,Medium
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,NaN,Dakar,...,TEC-CO-6011,Technology,Copiers,"Sharp Wireless Fax, High-Speed","$2,832.96",8,0.0,$311.52,903.04,Critical
5,22732,IN-2014-JM156557-41818,2014-06-28,2014-07-01,Second Class,JM-156557,Jim Mitchum,Corporate,NaN,Sydney,...,TEC-PH-5842,Technology,Phones,"Samsung Smart Phone, with Caller ID","$2,862.68",5,0.1,$763.28,897.35,Critical
6,30570,IN-2012-TS2134092-41219,2012-11-06,2012-11-08,First Class,TS-2134092,Toby Swindell,,NaN,Porirua,...,FUR-CH-5378,Furniture,Chairs,"Novimex Executive Leather Armchair, Adjustable","$1,822.08",4,0.0,$564.84,894.77,Critical
7,31192,IN-2013-MB1808592-41378,2013-04-14,2013-04-18,Standard Class,MB-1808592,Mick Brown,Consumer,NaN,Hamilton,...,FUR-TA-3764,Furniture,Tables,"Chromcraft Conference Table, Fully Assembled","$5,244.84",6,0.0,$996.48,878.38,High
8,40099,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,FUR-BO-5957,Furniture,Bookcases,"Sauder Facets Collection Library, Sky Alder Fi...",$341.96,2,0.0,$54.71,25.27,High
9,36258,CA-2012-AB10015140-40974,2012-03-06,2012-03-07,First Class,AB-100151404,Aaron Bergman,Consumer,98103.0,Seattle,...,FUR-CH-4421,Furniture,Chairs,"Global Push Button Manager's Chair, Indigo",$48.71,1,0.2,$5.48,11.13,High

In [44]:
df.to_json('sales.json',index=False)

In [45]:
df = pd.read_json("sales.json")
df.head()

,TransactionID,CustomerID,AccountID,AccountType,TransactionType,Product,Firm,Region,Manager,TransactionDate,TransactionAmount,AccountBalance,RiskScore,CreditRating,TenureMonths
0,118,CUST3810,ACC49774,Savings,Deposit,Credit Card,Firm D,West,Manager 4,1722470400000,20664.409820,88483.42208,0.483333,522,29
1,102,CUST3109,ACC96277,Savings,Deposit,Mutual Fund,Firm B,North,Manager 4,17-12-2023,94924.359120,56670.15864,0.788989,686,130
2,151,CUST2626,ACC21429,Credit,Payment,Personal Loan,Firm C,West,Manager 1,22-05-2024,-7871.160407,84968.05587,0.547782,618,157
3,57,CUST3725,ACC48501,Loan,Withdrawal,Credit Card,Firm A,East,Manager 4,24-12-2023,24979.808160,115196.96420,0.125587,803,155
4,113,CUST4258,ACC11285,Loan,Transfer,Home Loan,Firm A,West,Manager 4,15-01-2023,72890.748550,111602.76610,1.048787,657,68

In [47]:
df['TransactionDate'] = pd.to_datetime(
    df['TransactionDate'],
    dayfirst=True,
    errors='coerce'
)

In [48]:
df.to_parquet("sales.parquet", index=False)

In [49]:
df = pd.read_parquet("sales.parquet")
df.head(3)

,TransactionID,CustomerID,AccountID,AccountType,TransactionType,Product,Firm,Region,Manager,TransactionDate,TransactionAmount,AccountBalance,RiskScore,CreditRating,TenureMonths
0,118,CUST3810,ACC49774,Savings,Deposit,Credit Card,Firm D,West,Manager 4,1970-01-01 00:28:42.470400,20664.409820,88483.42208,0.483333,522,29
1,102,CUST3109,ACC96277,Savings,Deposit,Mutual Fund,Firm B,North,Manager 4,2023-12-17 00:00:00.000000,94924.359120,56670.15864,0.788989,686,130
2,151,CUST2626,ACC21429,Credit,Payment,Personal Loan,Firm C,West,Manager 1,2024-05-22 00:00:00.000000,-7871.160407,84968.05587,0.547782,618,157

In [52]:
json_data = df.to_json('data.json',orient='split')

In [53]:
df_new = pd.read_json("data.json", orient="split")
df_new.head()

,TransactionID,CustomerID,AccountID,AccountType,TransactionType,Product,Firm,Region,Manager,TransactionDate,TransactionAmount,AccountBalance,RiskScore,CreditRating,TenureMonths
0,118,CUST3810,ACC49774,Savings,Deposit,Credit Card,Firm D,West,Manager 4,1722470,20664.409820,88483.42208,0.483333,522,29
1,102,CUST3109,ACC96277,Savings,Deposit,Mutual Fund,Firm B,North,Manager 4,1702771200000,94924.359120,56670.15864,0.788989,686,130
2,151,CUST2626,ACC21429,Credit,Payment,Personal Loan,Firm C,West,Manager 1,1716336000000,-7871.160407,84968.05587,0.547782,618,157
3,57,CUST3725,ACC48501,Loan,Withdrawal,Credit Card,Firm A,East,Manager 4,1703376000000,24979.808160,115196.96420,0.125587,803,155
4,113,CUST4258,ACC11285,Loan,Transfer,Home Loan,Firm A,West,Manager 4,1673740800000,72890.748550,111602.76610,1.048787,657,68